# Generated by Django 3.2.2 on 2021-05-10 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, verbose_name='токен')),
                ('confirmation_type', models.CharField(choices=[('REG', 'Регистрация'), ('RESET', 'Сброс пароля')], max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
